pull_request_rules:
  - name: backport to maintained branches
    conditions:
      - base~=^(main|v4|v4-ics|v5|v6)$
      - label=BACKPORT
    actions:
      backport:
        branches:
          - main
          - v4-ics
          - v4
          - v5
          - v6
        assignees: 
            - "{{ author }}"
        labels:
          - automerge
          - backported
        title: "`[BP: {{ destination_branch }} <- #{{ number }}]` {{ title }}"

  - name: automerge backported PR's for maintained branches
    conditions:
      - label=automerge
      - base~=^(v4|v4-ics|v5|v6)$
    actions:
      merge:
        method: squash