name: Run Go Tests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'

jobs:
  test:
    name: run tests
    runs-on: [self-hosted, linux]
    steps:
      # Install and setup go
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # checkout ibc-test-framework
      - name: checkout ibc-test-framework
        uses: actions/checkout@v2

      # cleanup docker environment on self-hosted test runner
      # - name: prepare fresh docker environment
      #   run: |
      #     docker stop $(docker ps -a -q) || true
      #     docker rm -f $(docker ps -a -q) || true
      #     docker network prune -f || true

      # run tests
      - name: run tests
        run: go test -timeout 30m -v -p 1 ./...
