name: Run Go Tests

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'

jobs:
  test:
    name: all tests
    runs-on: [self-hosted, linux]
    steps:
      # Install and setup go
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # checkout ibc-test-framework
      - name: checkout ibc-test-framework
        uses: actions/checkout@v2

      # cleanup docker environment on self-hosted test runner
      # - name: prepare fresh docker environment
      #   run: |
      #     docker stop $(docker ps -a -q) || true
      #     docker rm -f $(docker ps -a -q) || true
      #     docker network prune -f || true

      # run tests
      # TODO: add me back!
#      - name: unit tests
#        run: make test

      - name: ibctest
        # DELETEME: temporary
        run: (make ibctest && cat doesnotexist) || cat ($HOME/.ibctest/logs/ibctest.log && exit 1)
